# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 11:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorterGroup',
            fields=[
            ],
            options={
                'permissions': [('read_group', 'Can access detailed view for groups.'), ('view_group', 'Can access the group application.')],
                'proxy': True,
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('read_issue', 'Can access detailed view for issues.'), ('view_issue', 'Can access the issue application.')]},
        ),
        migrations.AlterModelOptions(
            name='issuelog',
            options={'permissions': [('read_issuelog', 'Can access detailed view for issue logs.'), ('view_issuelog', 'Can access the issue log application.')]},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'permissions': [('read_label', 'Can access detailed view for labels.'), ('view_label', 'Can access the label application.')]},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'permissions': [('read_milestone', 'Can access detailed view milestones.'), ('view_milestone', 'Can access the user milestone application.')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('read_userprojectrole', 'Can access detailed view for user project role.'), ('view_userprojectrole', 'Can access the user project role application.')]},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': [('read_repository', 'Can access detailed view for repositories.'), ('view_repository', 'Can access the user repository application.')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('read_user', 'Can access detailed view for users.'), ('view_user', 'Can access the user application.')]},
        ),
        migrations.AlterModelOptions(
            name='userprojectrole',
            options={'permissions': [('read_userprojectrole', 'Can access detailed view for user project role.'), ('view_userprojectrole', 'Can access the user project role application.')]},
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='repository',
        ),
        migrations.AddField(
            model_name='issuelog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 14, 11, 29, 58, 404718, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='project',
            field=models.ManyToManyField(related_name='project_roles', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Milestone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='user',
            field=models.ManyToManyField(related_name='user_roles', to='core.User'),
        ),
    ]
