# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160414_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.Milestone'),
        ),
    ]
