# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160418_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('view_issue', 'Can view issues inside a project.')]},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'permissions': [('view_label', 'Can see labels.')]},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'permissions': [('view_milestone', 'Can see milestone.')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_projects', 'Can view all existing projects.')]},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': [('view_repository', 'Can see repositories inside a project.')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('read_user', 'Can access detailed view for users.'), ('view_user', 'Can access the user application.'), ('add_member', 'Can add members to a project'), ('remove_member', 'Can remove members from a project'), ('assign_role', 'Can assign roles to members')]},
        ),
    ]
