# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160429_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('view_issue', 'Can view issues inside a project.'), ('can_change_own_issue', 'Can only change owned issues'), ('can_close_issue', 'Can close issues')]},
        ),
    ]
