# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20160429_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectrole',
            name='project',
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
