# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160429_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('read_user', 'Can access detailed view for users.'), ('view_user', 'Can access the user application.'), ('view_member', 'Can access the list of project members'), ('add_member', 'Can add members to a project'), ('remove_member', 'Can remove members from a project'), ('assign_role', 'Can assign roles to members')]},
        ),
    ]
