# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160504_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porteruser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
