# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160504_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porteruser',
            name='user',
        ),
    ]
