# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_porteruser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
    ]
